### PR TITLE
[Tests] Split yaspgrid tests into multiple ones in a separate directo…

### PR DESCRIPTION
**Pull request by linusseelinger**
…ry, reduced run time for 3d case

### CODE REVIEW

**Comment by dokempf** [comment]
Another nice thing would be to add parallel tests. Those should
* be guarded by if(MPI_FOUND) in the CMakeLists.txt
* Use the variables exported by FindMPI.cmake (check cmake --help-module FindMPI)
* Take care that the size of the grid is sufficient!

**Comment by LSenf** [comment]
Included the changes you proposed

**Comment by LSenf** [comment]
Refinement tests only pass with the recent fix for refinement

**Comment by smuething** [comment]
Could you please split the last commit into separate commits that add the new test header and one each for the YaspGrid and the UGGrid test?

**Comment by smuething** [comment]
And please leave the actual test functionality in the Dune::GridCheck namespace. It's bad enough that we already clutter the global namespace with the old tests, we don't have to add to that. Also, by keeping it in the namespace, you don't have to qualify everything with `Dune::`, which improves readability quite a bit IMHO.

**Comment by LSenf** [comment]
Added the GridCheck namespace, split up the com check commits, rebased to current master

**Comment by dokempf** [comment]
@linusseelinger Assuming this has been handled with on Gitlab

**Pull request closed without merging**
